### ISSUE TITLE
Null class reserved in php7

### ISSUE THREAD

**Issue by elabayoub** [netgen/ezpublish-kernel#58]
Hey,
I'am trying to use this repo with php7, but unfortunately 'Null' can't be used as a name because it's reserved for php7. I have changed the name and it's usages manually its works, but i need a stable version for my composer.
Best Ragards.

**Comment by emodric** [comment]
Hi,

It was never the intention of this repo to provide the support for PHP 7. This was already discussed here: https://github.com/netgen/ezpublish-kernel/pull/22. The purpose of this repo is to provide bugfixes for an old unmaintained version of eZ Publish Kernel 2014.11 which never supported PHP 7 in the first place.

If you wish to use PHP 7 with eZ, you should switch to [eZ Platform](https://github.com/ezsystems/ezplatform)
